sudo: required
language: java
jdk: oraclejdk11


branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "nvt-kts-12"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=false -B
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_KEY