sudo: required
language: java
jdk: oraclejdk11


branches:
  only:
    - master

services:
  - mysql

ignore:
  - src/test/java/nvt.kts.ticketapp/e2e

addons:
  sonarcloud:
    organization: "nvt-kts-12"
    token: $SONAR_TOKEN # encrypted value of your token

before_install:
  - chmod +x mvnw

before_script:
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root


script:
  - ./mvnw clean install -DskipTests=false -B
  - ./mvnw sonar:sonar -Dsonar.projectKey=nvt-kts-12_backend -Dsonar.organization=nvt-kts-12 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
