sudo: required
language: java
jdk: oraclejdk11


branches:
  only:
    - master

services:
  - mysql

addons:
  sonarcloud:
    organization: "nvt-kts-12"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

before_install:
  - chmod +x mvnw

before_script:
  -  sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"

script:
  - ./mvnw clean install -DskipTests=false -B
  - ./mvnw sonar:sonar -Dsonar.projectKey=$SONAR_KEY -Dsonar.organization=nvt-kts-12 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN